package com.govproc.timeline.domain;

public enum ProcessEventType {
    PROCESS_CAPTURED,
    ANALYSIS_STARTED,
    ANALYSIS_APPROVED,
    ANALYSIS_REJECTED,
    QUOTATION_STARTED,
    QUOTATION_ADDED,
    QUOTATION_SELECTED,
    PROCESS_QUOTED,
    DISPUTE_STARTED,
    MARKED_AS_WINNER,
    MARKED_AS_LOSER,
    POST_BID_STARTED,
    POST_BID_HOMOLOGATED,
    POST_BID_ADJUDICATED,
    POST_BID_COMPLETED,
    CONTRACT_ACTIVATED,
    COMMITMENT_REGISTERED,
    INVOICE_REGISTERED,
    ADDENDUM_APPLIED,
    PROCESS_CLOSED
}
