package com.govproc.timeline.domain;

public enum ProcessEventType {
    PROCESS_CAPTURED,
    ANALYSIS_STARTED,
    ANALYSIS_APPROVED,
    ANALYSIS_REJECTED,
    QUOTATION_STARTED,
    QUOTATION_ADDED,
    QUOTATION_SELECTED,
    PROCESS_QUOTED,
    DISPUTE_STARTED,
    MARKED_AS_WINNER,
    MARKED_AS_LOSER,
    CONTRACT_ACTIVATED,
    PROCESS_CLOSED
}
